name: Go Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get Code
        uses: actions/checkout@v4

      - name: Build example
        run: GOOS=wasip1 GOARCH=wasm go build -o examples/go/app.wasm examples/go/main.go

      - name: Test
        run: go test ./internal/*
